CONNECT sys AS sysdba

DROP USER fortisbank CASCADE;

CREATE USER C##fortisbank IDENTIFIED BY 1234;

GRANT ALL PRIVILEGES TO C##fortisbank;

CONNECT C##fortisbank/1234;

--DROP TABLE account_has_transaction;
--DROP TABLE customer_has_account;
--DROP TABLE lineofcreditaccount;
--DROP TABLE creditaccount;
--DROP TABLE currencyaccount;
--DROP TABLE savingaccount;
--DROP TABLE checkingaccount;
--DROP TABLE transactionbank;
--DROP TABLE accountbank;
--DROP TABLE customerbank;
--DROP TABLE managerbank;
--DROP TABLE userbank;

CREATE TABLE userbank (
    userid NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, 
    username VARCHAR2(30) NOT NULL ,
    password NUMBER(6) NOT NULL 
);

ALTER TABLE userbank ADD CONSTRAINT pk_user PRIMARY KEY (userid);
ALTER TABLE userbank ADD CONSTRAINT unique_user UNIQUE (username);

CREATE TABLE managerbank (
    mgrid NUMBER NOT NULL,
    CONSTRAINT pk_manager PRIMARY KEY (mgrid),
    CONSTRAINT fk_managerbank_userid FOREIGN KEY (mgrid) REFERENCES userbank (userid) ON DELETE CASCADE
);

CREATE TABLE customerbank (
    customerid NUMBER NOT NULL,
    salary NUMBER (10,2),
    mgrid NUMBER NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (customerid),
    CONSTRAINT fk_customerbank_customerid FOREIGN KEY (customerid) REFERENCES userbank (userid) ON DELETE CASCADE,
    CONSTRAINT fk_customerbank_mgrid FOREIGN KEY (mgrid) REFERENCES managerbank (mgrid));

CREATE TABLE accountbank (
    accountid NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, 
    typeaccount VARCHAR2(20) NOT NULL ,
    customerid NUMBER NOT NULL,
    balance NUMBER(14,2) NOT NULL,
    openingdate DATE NOT NULL,
    CONSTRAINT fk_accountbank_customerid FOREIGN KEY (customerid) REFERENCES customerbank (customerid) ON DELETE CASCADE
);

ALTER TABLE accountbank ADD CONSTRAINT pk_account PRIMARY KEY (accountid);

CREATE TABLE transactionbank (
    transactionid NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, 
    description VARCHAR2(30),
    transactiondate DATE NOT NULL,
    amount NUMBER(11,2) NOT NULL,
    accountid NUMBER NOT NULL,
    typetransaction VARCHAR(20) NOT NULL,
    CONSTRAINT fk_transactionbank_accountid FOREIGN KEY (accountid) REFERENCES accountbank (accountid) ON DELETE CASCADE
);

ALTER TABLE transactionbank ADD CONSTRAINT pk_transaction PRIMARY KEY (transactionid);

CREATE TABLE checkingaccount (
    checkingaccountid NUMBER NOT NULL,
    month_trans_limit NUMBER (2) NOT NULL,
    trans_fee NUMBER (5,2),
    CONSTRAINT pk_checkigaccount PRIMARY KEY (checkingaccountid),
    CONSTRAINT fk_checkigaccount_checkingaccountid FOREIGN KEY (checkingaccountid) REFERENCES accountbank (accountid) ON DELETE CASCADE
);

CREATE TABLE savingaccount (
    savingsaccountid NUMBER NOT NULL,
    interest_rate NUMBER (4,2),
    gain NUMBER (14,2),
    due_date DATE NOT NULL,
    CONSTRAINT pk_savingsaccount PRIMARY KEY (savingsaccountid),
    CONSTRAINT fk_savingsaccount_savingsaccountid FOREIGN KEY (savingsaccountid) REFERENCES accountbank (accountid) ON DELETE CASCADE
);

CREATE TABLE currencyaccount (
    currencyaccountid NUMBER NOT NULL,
    currency VARCHAR (3) NOT NULL,
    currency_rate NUMBER (4,2),
    conv_fee NUMBER (14,2),
    CONSTRAINT pk_currencyaccount PRIMARY KEY (currencyaccountid),
    CONSTRAINT fk_currencyaccount_currencyaccountid FOREIGN KEY (currencyaccountid) REFERENCES accountbank (accountid) ON DELETE CASCADE
);

CREATE TABLE creditaccount (
    creditaccountid NUMBER NOT NULL,
    duedate DATE NOT NULL,
    limit NUMBER (14,2),
    CONSTRAINT pk_creditaccount PRIMARY KEY (creditaccountid),
    CONSTRAINT fk_creditaccount_creditaccountid FOREIGN KEY (creditaccountid) REFERENCES accountbank (accountid) ON DELETE CASCADE
);

CREATE TABLE lineofcreditaccount (
    lineofcreditaccountid NUMBER NOT NULL,
    interest_rate NUMBER (4,2),
    nbofinstall NUMBER(3),
    installment NUMBER (8,2),
    CONSTRAINT pk_lineofcreditaccount PRIMARY KEY (lineofcreditaccountid),
    CONSTRAINT fk_lineofcreditaccount_lineofcreditaccountid FOREIGN KEY (lineofcreditaccountid) REFERENCES creditaccount (creditaccountid) ON DELETE CASCADE
);

CREATE TABLE customer_has_account (
    customerid NUMBER NOT NULL,
    accountid NUMBER NOT NULL,
    CONSTRAINT pk_customerhasaccount PRIMARY KEY (customerid,accountid),
    CONSTRAINT fk_customerhasaccount_customerid FOREIGN KEY (customerid) REFERENCES customerbank (customerid) ON DELETE CASCADE,
    CONSTRAINT fk_customerhasaccount_accountid FOREIGN KEY (accountid) REFERENCES accountbank (accountid) ON DELETE CASCADE
);

CREATE TABLE account_has_transaction (
    accountid NUMBER NOT NULL,
    transactionid NUMBER NOT NULL,
    CONSTRAINT pk_accounthastransaction PRIMARY KEY (accountid, transactionid),
    CONSTRAINT fk_accounthastransaction_accountid FOREIGN KEY (accountid) REFERENCES accountbank (accountid) ON DELETE CASCADE,
    CONSTRAINT fk_accounthastransaction_transactionid FOREIGN KEY (transactionid) REFERENCES transactionbank (transactionid) ON DELETE CASCADE
);

INSERT INTO userbank VALUES (null,'John','1234');
INSERT INTO userbank VALUES (null,'Mary','1234');
INSERT INTO userbank VALUES (null,'Bruno','1234');
INSERT INTO userbank VALUES (null,'Kathleen','1234');
INSERT INTO userbank VALUES (null,'Clara','1234');

INSERT INTO managerbank VALUES (1);
INSERT INTO managerbank VALUES (2);

INSERT INTO customerbank VALUES (3,90000,1);
INSERT INTO customerbank VALUES (4,90000,2);
INSERT INTO customerbank VALUES (5,90000,1);

INSERT INTO accountbank VALUES (null,'CheckingAccount',3,50000,TO_DATE('2022-08-25', 'YYYY-MM-DD'));
INSERT INTO accountbank VALUES (null,'CheckingAccount',4,50000,TO_DATE('2022-08-26', 'YYYY-MM-DD'));
INSERT INTO accountbank VALUES (null,'CheckingAccount',5,50000,TO_DATE('2022-08-27', 'YYYY-MM-DD'));

INSERT INTO checkingaccount VALUES (1,3,10);
INSERT INTO checkingaccount VALUES (2,4,15);
INSERT INTO checkingaccount VALUES (3,5,20);

INSERT INTO customer_has_account VALUES (3,1);
INSERT INTO customer_has_account VALUES (4,2);
INSERT INTO customer_has_account VALUES (5,3);

COMMIT;